version: "3"

x-streamer-base: &streamer-base
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - shared
  volumes:
    - ./logs:/usr/src/logs
  env_file:
    - .env

services:
  streamer-bybit:
    <<: *streamer-base
    container_name: streamer-bybit
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bybit:/usr/src/output
    env_file:
      - .env
      - .env.bybit
    environment:
      - STREAMER_EXCHANGE=bybit

  streamer-bingx:
    <<: *streamer-base
    container_name: streamer-bingx
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bingx:/usr/src/output
    env_file:
      - .env
      - .env.bingx
    environment:
      - STREAMER_EXCHANGE=bingx

  streamer-bitget:
    <<: *streamer-base
    container_name: streamer-bitget
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bitget:/usr/src/output
    env_file:
      - .env
      - .env.bitget
    environment:
      - STREAMER_EXCHANGE=bitget

  streamer-binance:
    <<: *streamer-base
    container_name: streamer-binance
    volumes:
      - ./logs:/usr/src/logs
      - ./output/binance:/usr/src/output
    env_file:
      - .env
      - .env.binance
    environment:
      - STREAMER_EXCHANGE=binance

  streamer-okx:
    <<: *streamer-base
    container_name: streamer-okx
    volumes:
      - ./logs:/usr/src/logs
      - ./output/okx:/usr/src/output
    env_file:
      - .env
      - .env.okx
    environment:
      - STREAMER_EXCHANGE=okx

  streamer-proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: streamer-proxy
    networks:
      - shared
    volumes:
      - ./logs:/usr/src/logs
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - streamer-bybit
      - streamer-bingx
      - streamer-bitget
      - streamer-binance
      - streamer-okx

networks:
  shared:
    external: true
