version: "3"

services:
  streamer-bybit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-bybit
    networks:
      - shared
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bybit:/usr/src/output
    env_file:
      - .env
      - .env.bybit
    environment:
      - STREAMER_EXCHANGE=bybit

  streamer-bingx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-bingx
    networks:
      - shared
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bingx:/usr/src/output
    env_file:
      - .env
      - .env.bingx
    environment:
      - STREAMER_EXCHANGE=bingx

  streamer-proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: streamer-proxy
    networks:
      - shared
    volumes:
      - ./logs:/usr/src/logs
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - streamer-bybit
      - streamer-bingx

networks:
  shared:
    external: true
