version: "3"

networks:
  traefiktointernet:
    external: true
  shared:
    external: true

services:
  streamer-bybit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-bybit
    networks:
      - traefiktointernet
      - shared
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bybit:/usr/src/output
    env_file:
      - .env
      - .env.bybit
    environment:
      - STREAMER_EXCHANGE=bybit

  streamer-bingx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-bingx
    networks:
      - traefiktointernet
      - shared
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bingx:/usr/src/output
    env_file:
      - .env
      - .env.bingx
    environment:
      - STREAMER_EXCHANGE=bingx

  streamer-bitget:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer-bitget
    networks:
      - traefiktointernet
      - shared
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bitget:/usr/src/output
    env_file:
      - .env
      - .env.bitget
    environment:
      - STREAMER_EXCHANGE=bitget

  streamer-proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: streamer-proxy
    networks:
      - traefiktointernet
      - shared
    volumes:
      - ./logs:/usr/src/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefiktointernet

      - traefik.http.routers.streamer-proxy.entrypoints=websecure
      - traefik.http.routers.streamer-proxy.rule=Host(`${STREAMER_HOST}`)
      - traefik.http.routers.streamer-proxy.tls=true
      - traefik.http.routers.streamer-proxy.tls.certresolver=letsencrypt

      - traefik.http.services.streamer-proxy.loadbalancer.server.port=${PROXY_WEBSOCKET_PORT}
    environment:
      - PROXY_WSS_AUTH_KEY=${STREAMER_WSS_AUTH_KEY}
      - PROXY_WSS_AUTH_USER=${STREAMER_WSS_AUTH_USER}
    env_file:
      - .env
    depends_on:
      - streamer-bybit
      - streamer-bingx
      - streamer-bitget
