version: "3"

networks:
  traefiktointernet:
    external: true
  shared:
    external: true

x-streamer-base: &streamer-base
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - traefiktointernet
    - shared
  volumes:
    - ./logs:/usr/src/logs
  env_file:
    - .env

services:
  streamer-bybit:
    <<: *streamer-base
    container_name: streamer-bybit
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bybit:/usr/src/output
    env_file:
      - .env
      - .env.bybit
    environment:
      - STREAMER_EXCHANGE=bybit

  streamer-bingx:
    <<: *streamer-base
    container_name: streamer-bingx
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bingx:/usr/src/output
    env_file:
      - .env
      - .env.bingx
    environment:
      - STREAMER_EXCHANGE=bingx

  streamer-bitget:
    <<: *streamer-base
    container_name: streamer-bitget
    volumes:
      - ./logs:/usr/src/logs
      - ./output/bitget:/usr/src/output
    env_file:
      - .env
      - .env.bitget
    environment:
      - STREAMER_EXCHANGE=bitget

  streamer-binance:
    <<: *streamer-base
    container_name: streamer-binance
    volumes:
      - ./logs:/usr/src/logs
      - ./output/binance:/usr/src/output
    env_file:
      - .env
      - .env.binance
    environment:
      - STREAMER_EXCHANGE=binance

  streamer-okx:
    <<: *streamer-base
    container_name: streamer-okx
    volumes:
      - ./logs:/usr/src/logs
      - ./output/okx:/usr/src/output
    env_file:
      - .env
      - .env.okx
    environment:
      - STREAMER_EXCHANGE=okx

  streamer-proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: streamer-proxy
    networks:
      - traefiktointernet
      - shared
    volumes:
      - ./logs:/usr/src/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefiktointernet
      - traefik.http.routers.streamer-proxy.entrypoints=websecure
      - traefik.http.routers.streamer-proxy.rule=Host(`${STREAMER_HOST}`)
      - traefik.http.routers.streamer-proxy.tls=true
      - traefik.http.routers.streamer-proxy.tls.certresolver=letsencrypt
      - traefik.http.services.streamer-proxy.loadbalancer.server.port=${PROXY_WEBSOCKET_PORT}
    environment:
      - PROXY_WSS_AUTH_KEY=${STREAMER_WSS_AUTH_KEY}
      - PROXY_WSS_AUTH_USER=${STREAMER_WSS_AUTH_USER}
    env_file:
      - .env
    depends_on:
      - streamer-bybit
      - streamer-bingx
      - streamer-bitget
      - streamer-binance
      - streamer-okx
